rest_entry:
  prefork: false
  views:
    dir: "templates"
    ext: ".html"
oss:
  default:
    endpoint: "{{env_oss_endpoint}}"
    accessKeyID: "{{env_oss_ak}}"
    accessKeySecret: "{{env_oss_sk}}"
    bucket: "kooksee"
watcher:
  default:
    driver: file
ossync:
  test: "sss"
db:
  default:
    driver: "sqlite3_golug"
    source: "{{home}}/db/sqlite.db"
log:
  level: debug
  encoderConfig:
    callerEncoder: full
